/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as liquidatooorV3TestingSol from "./LiquidatooorV3Testing.sol";
export type { liquidatooorV3TestingSol };
