/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { LiquidatooorV2__factory } from "./LiquidatooorV2__factory";
