/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlashLoanReceiverBase } from "./FlashLoanReceiverBase";
export type { IERC20 } from "./IERC20";
export type { IFlashLoanReceiver } from "./IFlashLoanReceiver";
export type { ILendingPool } from "./ILendingPool";
export type { ILendingPoolAddressesProvider } from "./ILendingPoolAddressesProvider";
