/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDex,
  IDexInterface,
} from "../../../../../contracts/aave-v3/testing/LiquidatooorV3Testing.sol/IDex";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
    ],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "sellWeth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "wethToDaiRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDex__factory {
  static readonly abi = _abi;
  static createInterface(): IDexInterface {
    return new utils.Interface(_abi) as IDexInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IDex {
    return new Contract(address, _abi, signerOrProvider) as IDex;
  }
}
